name: publish

on:
  push:
    branches: main

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/alves-dev/life-assistant-link:latest
#          docker run ghcr.io/alves-dev/life-assistant-link:latest
          docker push ghcr.io/alves-dev/life-assistant-link:latest