name: publish

on:
  push:
    branches: main

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Set up python
        uses: actions/setup-python@v5
      -
        name: Install Poetry
        uses: snok/install-poetry@v1
      -
        name: Generate requirements.txt
        run: poetry export --without-hashes --format=requirements.txt > requirements.txt
      -
        name: login gh
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/alves-dev/life-assistant-link:latest
          docker push ghcr.io/alves-dev/life-assistant-link:latest