name: publish

on:
  push:
    branches: main

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Set up python
        uses: actions/setup-python@v5
      -
        name: Install Poetry
        uses: snok/install-poetry@v1
      -
        name: Generate requirements.txt
        run: poetry export --without-hashes --format=requirements.txt > requirements.txt
      -
        name: Login in ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push Docker image
        run: |
          docker buildx create --use --name mybuilder
          docker buildx build . --platform linux/amd64,linux/arm64 --tag ghcr.io/alves-dev/life-assistant-link:latest --push
#          docker build . --tag ghcr.io/alves-dev/life-assistant-link:latest
#          docker push ghcr.io/alves-dev/life-assistant-link:latest
#docker buildx build . --platform linux/amd64,linux/arm64,linux/arm/v7 --tag igor:latest
#docker buildx build --platform linux/amd64,linux/arm64 --tag igor:latest .